#
# Module manifest for module 'OctoPwsh'
#
# Generated by: Michael Levan
#
# Generated on: 1/23/2020
#

@{

# Script module or binary module file associated with this manifest.
# RootModule = ''

# Version number of this module.
ModuleVersion = '1.0'

# Supported PSEditions
 CompatiblePSEditions = @('Powershell Core (all versions)')

# ID used to uniquely identify this module
GUID = 'd63aae67-7bee-40a3-9188-d8ca73e8c4be'

# Author of this module
Author = 'Michael Levan'

# Copyright statement for this module
Copyright = '(c) Michael Levan. All rights reserved.'

# Description of the functionality provided by this module
 Description = 'OctoPwsh is for the coders that do not want to interact with Octopus Deploy via the UI and instead want to use PowerShell.'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '7.0'

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @()

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{}

}

